/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiPenampilGambar;

import java.awt.CardLayout;

/**
 *
 * @author Nanda Fitzki
 */
public class PilihGambarComboBOX extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarComboBOX() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilihcombobox = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        SebuahCicipanSurgawiLB = new javax.swing.JLabel();
        InterstellarLB = new javax.swing.JLabel();
        KafirLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pilih Gambar");
        buttonPanel.add(jLabel1);

        pilihcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sebuah Cicipan Surgawi", "Interstellar", "Kafir" }));
        pilihcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihcomboboxItemStateChanged(evt);
            }
        });
        buttonPanel.add(pilihcombobox);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton4);

        imagePanel.setLayout(new java.awt.CardLayout());

        SebuahCicipanSurgawiLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SebuahCicipanSurgawiLB.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Uniska\\Semester 5\\PEMROGRAMAN BERBASIS OBJEK 2\\Praktek\\AplikasiPenampilGambar\\AplikasiPenampilGambar\\Gambar\\cicipan.jpg")); // NOI18N
        imagePanel.add(SebuahCicipanSurgawiLB, "0");

        InterstellarLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InterstellarLB.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Uniska\\Semester 5\\PEMROGRAMAN BERBASIS OBJEK 2\\Praktek\\AplikasiPenampilGambar\\AplikasiPenampilGambar\\Gambar\\interstelar.jpg")); // NOI18N
        imagePanel.add(InterstellarLB, "1");

        KafirLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KafirLB.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Uniska\\Semester 5\\PEMROGRAMAN BERBASIS OBJEK 2\\Praktek\\AplikasiPenampilGambar\\AplikasiPenampilGambar\\Gambar\\kafir.jpg")); // NOI18N
        imagePanel.add(KafirLB, "2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pilihcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihcomboboxItemStateChanged
       CardLayout c1 = (CardLayout) (imagePanel.getLayout());
       c1.show(imagePanel, String.valueOf(pilihcombobox.getSelectedIndex()));
    }//GEN-LAST:event_pilihcomboboxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBOX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBOX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBOX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBOX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarComboBOX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InterstellarLB;
    private javax.swing.JLabel KafirLB;
    private javax.swing.JLabel SebuahCicipanSurgawiLB;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> pilihcombobox;
    // End of variables declaration//GEN-END:variables
}
